### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by afritzler** [afritzler/virtual-gardener-gke#1]
Create a `Dockerfile` containing the following tooling:

* terraform https://www.terraform.io/
* yaml2json https://github.com/bronze1man/yaml2json
* jq https://github.com/stedolan/jq
* cfssl https://github.com/cloudflare/cfssl
* openssl https://github.com/openssl/openssl
* kubectl https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl
* helm https://github.com/helm/helm/releases

**Comment by Diaphteiros** [comment]
- spiff++ https://github.com/mandelsoft/spiff/releases

Should we add spiff here? It's not needed for this setup, but it will be needed for the community installer.

**Comment by afritzler** [comment]
We don't need spiff for this setup.

**Comment by afritzler** [comment]
Keep it simple and add a wrapper script to get you started with a docker run + volume mount of the project directory.
